global using System.ClientModel;
global using System.ComponentModel;
global using System.Text;
global using System.Text.Json;
global using AIExamples.Shared.Configuration;
global using AIExamples.Shared.Examples;
global using AIExamples.Shared.Examples.Attributes;
global using AIExamples.Shared.Extensions;
global using Azure;
global using Azure.AI.Agents.Persistent;
global using Azure.AI.OpenAI;
global using Azure.Identity;
global using Microsoft.Agents.AI;
global using Microsoft.Extensions.AI;
global using Microsoft.Extensions.DependencyInjection;
global using MicrosoftAgentFramework.Examples.Foundation.Models;
global using MicrosoftAgentFramework.Examples.Foundation.Services;
global using MicrosoftAgentFramework.Examples.Tools.Models;
global using MicrosoftAgentFramework.Examples.Tools.Services;
global using ModelContextProtocol.Client;
global using OpenAI;
global using OpenAI.Chat;
global using ChatMessage = Microsoft.Extensions.AI.ChatMessage;
global using ChatResponseFormat = Microsoft.Extensions.AI.ChatResponseFormat;
